<?php $this->load->view('layout/header');?>
	<div class="container"> 
		<h1>Perhitungan</h1>
		<br>
		<div>
			<h2>Tabel Aspek Kandungan Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Tabel Aspek Kandungan Non Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Tabel GAP Kandungan Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Tabel GAP Kandungan Non Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Ketentuan Pembobotan</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Selisih</th>
						<th>Bobot Nilai</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Angka</td>
						<td>Nilai</td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Pembobotan Kandungan Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Pembobotan Kandungan Non Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Perhitungan Factor Kandungan Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Perhitungan Factor Kandungan Non Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Perhitungan Nilai Total Kandungan Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Perhitungan Nilai Total Kandungan Non Asam</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>No</th>
						<th>Nama</th>
						<th>1</th>
						<th>2</th>
						<th>3</th>
						<th>4</th>
						<th>5</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
		<br>
		<div>
			<h2>Ranking</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Ranking</th>
						<th>Nama Alternatif</th>
						<th>Nilai Total</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>No</td>
						<td>Nama</td>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
<?php $this->load->view('layout/footer');?>

